### ISSUE TITLE
Loading keys from OpenID Connect metadata

### ISSUE THREAD

**Issue by leastprivilege** [dvsekhvalnov/jose-pcl#2]
Hi, 

doing some experiments - but I am stuck at creating the keys.

I need to pull the keys from an OIDC metadata document - e.g.

https://demo.identityserver.io/.well-known/jwks

There are two typical use cases:
- use the x5c (that a base64 encoded X509 cert)
- use the n and e (exponent and modulus)

Can you show me how to load the keys for both formats? thanks!

**Comment by dvsekhvalnov** [comment]
It is in JWK format. Probably i should add support for this finally. There were requests to support it for different implementations.

Are you looking for working with JWK keys dynamically (runtime) or just need to convert to static key for tests? If later checkout:  https://github.com/dvsekhvalnov/jose-rt#x509-public-subject-key-info

**Comment by leastprivilege** [comment]
Hi,

Dynamically..thanks

**Comment by leastprivilege** [comment]
A sample would be good enough for now to unblock me.

**Comment by dvsekhvalnov** [comment]
Ok, i'll take a look what's possible with PCLCrypto. I don't believe reading X509 cert is supported, because underlaying platform (WinRT) supports only X509 Public Key info structure.

**Comment by leastprivilege** [comment]
Rsa would be good enough for now

**Comment by dvsekhvalnov** [comment]
@leastprivilege , i added method to create pub rsa key from exponent and modulus. 

Checkout test: https://github.com/dvsekhvalnov/jose-pcl/blob/master/UnitTests/PublicKeyTest.cs#L86

Also pushed this to nuget.org, v0.0.3

I'll think about adding comprehensive JWK support later.

**Comment by leastprivilege** [comment]
Could you have a look at this

https://github.com/leastprivilege/JosePclTests

I am getting not supported exception

**Comment by dvsekhvalnov** [comment]
@leastprivilege , i added PCLCrypto explicitly to your project - and it is working.

Looks like something with transitive dependency from jose-pcl. Not sure at the moment,

**Comment by leastprivilege** [comment]
It only works for me when I update to PCLCrypto v2

**Comment by dvsekhvalnov** [comment]
mm..ok, i'll check (or upgrade dependency)

**Comment by dvsekhvalnov** [comment]
@leastprivilege , bump up PCLCrypto to v2, pushed v0.0.4 to nuget.org.

Give it a try.

**Comment by leastprivilege** [comment]
I will thanks!

— 
cheers
Dominick Baier

On 5 April 2016 at 12:35:38, dvsekhvalnov (notifications@github.com) wrote:

@leastprivilege , bump up PCLCrypto to v2, pushed v0.0.4 to nuget.org.

Give it a try.

**Comment by leastprivilege** [comment]
OK - Win & UWP is working fine. Xamarin next.

**Comment by leastprivilege** [comment]
Xamarin iOS works fine as well! Very cool.

The next thing I'd need is the ability to look at the header - I think that is not implemented yet for PCL.

I can do that manually of course.

**Comment by dvsekhvalnov** [comment]
open a ticket? )

**Comment by leastprivilege** [comment]
OK ;)

we can close this issue now - it is working well enough.

**Comment by leastprivilege** [comment]
thanks!
